AllCops:
  Exclude:
    - '.kitchen/**/*'
    - 'Berksfile'
    - 'test/fixtures/cookbooks/**/*'
    - 'Vagrantfile'

Encoding:
  Enabled: false

ClassLength:
  Max: 300

LineLength:
  Max: 200

MethodLength:
  Max: 10

TrivialAccessors:
  Enabled: true
  ExactNameMatch: true

DuplicatedKey:
  Enabled: false
