sudo: false
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

before_install:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

install: "bundle install --no-cache"

script:
  - rubocop
  - foodcritic -f any -f ~FC015 -X spec .
  - bundle exec rspec --color --format progress
